insert into disciplinas values('Eng-130','Algoritmos e Programação de Computadores I','60');
insert into disciplinas values('Eng-122','Cálculo Diferencial e Integral l', '90');
insert into disciplinas values('Eng-133','Desenho Técnico por Computador', '30');
insert into disciplinas values('Eng-0','Introdução à Engenharia de Computação', '30');
insert into disciplinas values('Eng-132','Lógica Aplicada à Computação', '60');
insert into disciplinas values('Eng-110', 'Português Instrumental','60');
insert into disciplinas values('Eng-270', 'Química Geral e Experimental', '60');
insert into disciplinas values('Eng-131','Algoritmos e Programação de Computadores II', '60');
insert into disciplinas values('Eng-123','Cálculo Diferencial e Integral II', '60');
insert into disciplinas values('Eng-171', 'Física Geral e Experimental I','60');
insert into disciplinas values('Eng-120', 'Geometria Analítica e de Vetores','60');
insert into disciplinas values('Eng-111','Inglês Instrumental', '30');
insert into disciplinas values('Eng-121', 'Álgebra Linear','60');
insert into disciplinas values('Eng-232', 'Arquitetura e Organização de Computadores I','60');
insert into disciplinas values('Eng-221', 'Cálculo Diferencial e Integral III', '60');
insert into disciplinas values('Eng-220', 'Cálculo Numérico', '60');
insert into disciplinas values('Eng-230','Estrutura de Dados', '60');
insert into disciplinas values('Eng-271', 'Física Geral e Experimental II', '60');
insert into disciplinas values('Eng-233', 'Arquitetura e Organização de Computadores II', '60');
insert into disciplinas values('Eng-235', 'Banco de Dados','60');
insert into disciplinas values('Eng-222', 'Equações Diferenciais', '60');
insert into disciplinas values('Eng-272', 'Física Geral e Experimental III', '60');
insert into disciplinas values('Eng-273', 'Mecânica Geral', '60');
insert into disciplinas values('Eng-250', 'Metodologia da Pesquisa Científica', '60');
insert into disciplinas values('Eng-370', 'Circuitos Elétricos I', '60');
insert into disciplinas values('Eng-373', 'Fenômenos de Transporte', '30');
insert into disciplinas values('Eng-332', 'Linguagens Formais e Autômatos', '60');
insert into disciplinas values('Eng-372', 'Resistência dos Materiais', '60');
insert into disciplinas values('Eng-334', 'Sistemas Operacionais', '60');
insert into disciplinas values('Eng-000','Sociologia', '60');
insert into disciplinas values('Eng-374', 'Análise de Sinais e Sistemas', '60');
insert into disciplinas values('Eng-437', 'Computação Gráfica', '60');
insert into disciplinas values('Eng-371', 'Eletrônica I', '60');
insert into disciplinas values('Eng-331', 'Engenharia de Software', '60');
insert into disciplinas values('Eng-320', 'Estatística e Probabilidade','60');
insert into disciplinas values('Eng-335', 'Redes de Computadores I', '60');
insert into disciplinas values('Eng-470', 'Circuitos Elétricos II', '60');
insert into disciplinas values('Eng-472', 'Controle I', '60');
insert into disciplinas values('Eng-375', 'Processamento Digital de Sinais','60');
insert into disciplinas values('Eng-471', 'Prototipação de Circuitos Digitais', '60');
insert into disciplinas values('Eng-434', 'Redes de Computadores II', '60');
insert into disciplinas values('EngG-550', 'Tecnologia de Gestão em Administração','60');
insert into disciplinas values('Eng-460', 'Ciências Sociais E Jurídicas', '30');
insert into disciplinas values('Eng-451', 'Empreendedorismo', '60');
insert into disciplinas values('Eng-435', 'Inteligência Artificial', '60');
insert into disciplinas values('Eng-475', 'Interface Homem X Máquina', '60');
insert into disciplinas values('Eng-474', 'Princípios de Comunicação', '60');
insert into disciplinas values('Eng-436', 'Sistemas Concorrentes e Distribuídos','60');
insert into disciplinas values('Eng-571', 'Automação Industrial', '60');
insert into disciplinas values('Eng-570', 'Engenharia de Sistemas Embarcados', '60');
insert into disciplinas values('Eng-581', 'Estágio Supervisionado I','30');
insert into disciplinas values('Eng-551','Gestão Ambiental e Desenvolvimento Sustentável', '60');
insert into disciplinas values('Eng-590','Trabalho Cientifico de Formatura I', '30');
insert into disciplinas values('Eng-386','Sistemas Microprocessados', '60');
insert into disciplinas values('Eng-500','Contabilidade Geral', '60');
insert into disciplinas values('Eng-540', 'Economia', '60');
insert into disciplinas values('Eng-582', 'Estágio Supervisionado II', '30');
insert into disciplinas values('Eng-591', 'Trabalho Científico de Formatura II', '30');


insert into pre_requisitos values('Eng-123','Eng-221');
insert into pre_requisitos values('Eng-171','Eng-271');
insert into pre_requisitos values('Eng-171','Eng-273');
insert into pre_requisitos values('Eng-221','Eng-222');
insert into pre_requisitos values('Eng-131','Eng-130');
insert into pre_requisitos values('Eng-131','Eng-230');
insert into pre_requisitos values('Eng-230','Eng-235');
insert into pre_requisitos values('Eng-120','Eng-121');
insert into pre_requisitos values('Eng-221','Eng-374');
insert into pre_requisitos values('Eng-273','Eng-372');
insert into pre_requisitos values('Eng-271','Eng-272');
insert into pre_requisitos values('Eng-272','Eng-370');
insert into pre_requisitos values('Eng-374','Eng-375');
insert into pre_requisitos values('Eng-122','Eng-123');
insert into pre_requisitos values('Eng-122','Eng-171');
insert into pre_requisitos values('Eng-122','Eng-220');
insert into pre_requisitos values('Eng-374','Eng-474');
insert into pre_requisitos values('Eng-370','Eng-371');
insert into pre_requisitos values('Eng-370','Eng-470');
insert into pre_requisitos values('Eng-232','Eng-233');
insert into pre_requisitos values('Eng-232','Eng-334');
insert into pre_requisitos values('Eng-335','Eng-434');
insert into pre_requisitos values('Eng-335','Eng-436');
insert into pre_requisitos values('Eng-271','Eng-373');
insert into pre_requisitos values('Eng-590','Eng-591');
insert into pre_requisitos values('Eng-581','Eng-582');